// Generated by CoffeeScript 1.10.0
(function() {
  var _, compData, dataFilePaths, env, fileWatcher, fs, globalData, loadData, path, urlData;

  fs = require("fs");

  path = require("path");

  fileWatcher = require("./file_watcher");

  env = require("./enviroments");

  _ = require("lodash");

  dataFilePaths = env.dataFiles;

  urlData = {};

  compData = {};

  globalData = {};

  loadData = function(dataFilePath) {
    var data;
    if (fs.existsSync(dataFilePath)) {
      data = require(dataFilePath);
      urlData = _.assign(urlData, data.urls);
      compData = _.assign(compData, data.comps);
      return globalData = _.assign(globalData, data.globals);
    }
  };

  _.each(dataFilePaths, loadData);

  fileWatcher.watchFiles(dataFilePaths, function(dataFilePath) {
    var err, error;
    require.cache[dataFilePath] = null;
    try {
      loadData(dataFilePath);
      return console.log("[Data Reload] " + dataFilePath);
    } catch (error) {
      err = error;
      return console.log("[Data Reload Error] " + dataFilePath + " - " + err);
    }
  });

  module.exports = {
    getUrlData: function(path, params, res) {
      var data;
      if (!_.has(urlData, path)) {
        return {
          found: false
        };
      }
      data = urlData[path];
      return {
        found: true,
        result: _.isFunction(data) ? data(params, res) : data
      };
    },
    getCompData: function(path, params) {
      var data;
      if (!_.has(compData, path)) {
        return {
          found: false
        };
      }
      data = compData[path];
      return {
        found: true,
        result: _.isFunction(data) ? data(params) : data
      };
    },
    getGlobalData: function() {
      return globalData;
    }
  };

}).call(this);
