// Generated by CoffeeScript 1.10.0
(function() {
  var FileNotFoundError;

  FileNotFoundError = (function() {
    function FileNotFoundError(path) {
      this.path = path;
    }

    return FileNotFoundError;

  })();

  module.exports = {
    FileNotFoundError: FileNotFoundError
  };

}).call(this);
